# Generated by Django 5.2.11 on 2026-02-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('menu', 'Menu'), ('ordering', 'Ordering'), ('inventory', 'Inventory')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='outlet',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Features enabled for this outlet', related_name='ouetlet_features', to='core.feature'),
        ),
    ]
