# Generated by Django 5.2.11 on 2026-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature_outlet_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
