# Generated by Django 5.2.11 on 2026-02-08 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='superadmin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OutletFeatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(to='core.feature')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_history', to='core.outlet')),
            ],
        ),
    ]
