# Generated by Django 5.2.11 on 2026-02-08 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outlet_superadmin_approved_outletfeaturehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletFeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, help_text='Reason for rejection or other notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(to='core.feature')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='core.outlet')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
