# Generated by Django 5.2.11 on 2026-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_outletfeaturerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
