# Generated by Django 5.2.11 on 2026-02-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_feature_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('menu', 'Menu'), ('ordering', 'Ordering'), ('inventory', 'Inventory')], max_length=50),
        ),
    ]
