# Generated by Django 5.2.11 on 2026-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletfeaturerequest',
            name='request_type',
            field=models.CharField(choices=[('add', 'Add Feature'), ('remove', 'Remove Feature')], default='add', max_length=10),
        ),
    ]
