# Generated by Django 5.2.11 on 2026-02-08 14:15

from django.db import migrations, models
import django.db.models.deletion

def seed_global_features(apps, schema_editor):
    """
    Populates the GlobalFeature table with the master features.
    """
    GlobalFeature = apps.get_model('core', 'GlobalFeature')
    GlobalFeature.objects.create(name="menu", slug="menu", description="Menu management feature.")
    GlobalFeature.objects.create(name="ordering", slug="ordering", description="Ordering and billing feature.")
    GlobalFeature.objects.create(name="inventory", slug="inventory", description="Inventory and stock management feature.")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outletfeaturerequest_request_type'),
    ]

    operations = [
        # Step 1: Create the new master model
        migrations.CreateModel(
            name='GlobalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('menu', 'Menu'), ('ordering', 'Ordering'), ('inventory', 'Inventory')], max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        # Step 2: Create the new 'through' model
        migrations.CreateModel(
            name='OutletFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.globalfeature')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
            options={
                'unique_together': {('outlet', 'global_feature')},
            },
        ),
        # Step 3: Seed the master model
        migrations.RunPython(seed_global_features),
        
        # Step 4: Remove the old M2M field from Outlet
        migrations.RemoveField(
            model_name='outlet',
            name='features',
        ),
        # Step 5: Add the new M2M field pointing to GlobalFeature through OutletFeature
        migrations.AddField(
            model_name='outlet',
            name='features',
            field=models.ManyToManyField(related_name='outlets_with_feature', through='core.OutletFeature', to='core.globalfeature'),
        ),
        
        # Step 6 & 7: Point the other M2M fields to the new GlobalFeature model
        migrations.AlterField(
            model_name='outletfeaturehistory',
            name='features',
            field=models.ManyToManyField(to='core.globalfeature'),
        ),
        migrations.AlterField(
            model_name='outletfeaturerequest',
            name='features',
            field=models.ManyToManyField(to='core.globalfeature'),
        ),
        
        # Step 8: Delete the old Feature model
        migrations.DeleteModel(
            name='Feature',
        ),
    ]