# Generated by Django 5.2.11 on 2026-02-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Menu', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Menu.menuitem'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'outlet')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together={('menu_item', 'ingredient')},
        ),
    ]
