# Generated by Django 5.2.3 on 2025-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_ingredient_is_active_ingredient_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, help_text='Items included in this order', related_name='orders', to='Inventory.orderitem'),
        ),
    ]
