# Generated by Django 5.2.3 on 2026-02-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_alter_monthlybillingcycle_outlet'),
        ('Inventory', '0002_alter_ingredient_outlet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
