# Generated by Django 5.2.3 on 2025-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_orderitem_order_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory_transactions',
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_transactions',
            field=models.ManyToManyField(blank=True, help_text='Inventory transactions related to this order item', related_name='order_items', to='Inventory.inventorytransaction'),
        ),
    ]
