# Generated by Django 5.2.3 on 2025-08-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0002_ingredient_is_active_ingredient_slug_and_more'),
        ('Restaurant', '0011_remove_orderitem_order_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(help_text='Month number (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of the billing cycle')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('orders', models.ManyToManyField(related_name='billing_cycles', to='Inventory.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.outlet')),
            ],
            options={
                'verbose_name': 'Monthly Billing Cycle',
                'verbose_name_plural': 'Monthly Billing Cycles',
                'unique_together': {('outlet', 'month', 'year')},
            },
        ),
    ]
