# Generated by Django 5.2.11 on 2026-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(help_text='Month number (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of the billing cycle')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Monthly Billing Cycle',
                'verbose_name_plural': 'Monthly Billing Cycles',
            },
        ),
    ]
