# Generated by Django 5.2.3 on 2026-03-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analysis', '0001_initial'),
        ('Ordering', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillingcycle',
            name='orders',
            field=models.ManyToManyField(related_name='billing_cycles', to='Ordering.order'),
        ),
        migrations.AddField(
            model_name='monthlybillingcycle',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybillingcycle',
            unique_together={('outlet', 'month', 'year')},
        ),
    ]
