# Generated by Django 5.2.11 on 2026-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analysis', '0001_initial'),
        ('Ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillingcycle',
            name='orders',
            field=models.ManyToManyField(related_name='billing_cycles', to='Ordering.order'),
        ),
    ]
