# Generated by Django 5.2.3 on 2026-02-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_alter_monthlybillingcycle_outlet'),
        ('Ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybillingcycle',
            name='orders',
            field=models.ManyToManyField(related_name='billing_cycles', to='Ordering.order'),
        ),
    ]
