# Generated by Django 5.2.11 on 2026-02-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analysis', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillingcycle',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybillingcycle',
            unique_together={('outlet', 'month', 'year')},
        ),
    ]
