# Generated by Django 5.2.3 on 2025-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
