# Generated by Django 5.2.3 on 2025-06-29 17:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_menucategory_display_order_menuitem_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Restaurant__search__f12252_gin'),
        ),
    ]
