# Generated by Django 5.2.3 on 2025-06-29 17:39

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_menucategory_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
