# Generated by Django 5.2.3 on 2025-06-29 18:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_alter_menucategory_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Restaurant__search__c006ea_gin'),
        ),
    ]
