# Generated by Django 5.2.3 on 2025-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_menuitem_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
