# Generated by Django 5.2.3 on 2025-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_categoryimage_menucategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('discount', 'Discount'), ('buy_one_get_one', 'Buy One Get One')], default='discount', max_length=100)),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Fixed Amount')], default='flat', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='Restaurant.offers'),
        ),
    ]
