# Generated by Django 5.2.3 on 2025-07-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0010_categoryimage_created_at_categoryimage_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
