# Generated by Django 5.2.3 on 2025-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_remove_orderitem_order_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_cover_images/'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='mid_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_mid_page_images/'),
        ),
    ]
