# Generated by Django 5.2.3 on 2025-12-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_outlet_cover_image_outlet_mid_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='mid_page_image',
        ),
        migrations.CreateModel(
            name='OutletSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='outlet_slider_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='Restaurant.outlet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
