# Generated by Django 5.2.3 on 2025-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_remove_outlet_mid_page_image_outletsliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsliderimage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
