# Generated by Django 5.2.3 on 2026-02-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0014_outletsliderimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_categories', to='Restaurant.outlet'),
        ),
    ]
