# Generated by Django 5.2.11 on 2026-02-10 12:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_categories', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menucategory'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='Menu.offers'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Menu_menuca_search__963dc8_gin'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Menu_menuit_search__3980e8_gin'),
        ),
    ]
