# Generated by Django 5.2.3 on 2026-02-08 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_alter_monthlybillingcycle_outlet'),
        ('Inventory', '0002_alter_ingredient_outlet_and_more'),
        ('Menu', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='outletsliderimage',
            name='outlet',
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_categories', to='core.outlet'),
        ),
        migrations.DeleteModel(
            name='Franchise',
        ),
        migrations.DeleteModel(
            name='OutletSliderImage',
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
    ]
